kind: ConfigMap
apiVersion: v1
metadata:
  name: azure-appconfig-kubernetes
data:
  bootstrap-kubernetes.yaml: |
    azure:
      storages:
        sa202008:
          name: 202008FromConfigMap
          key: 202008FromConfigMap
        sa202009:
          name: ${SA202009_NAME:notprovided}
          key: ${SA202009_KEY:notprovided}
        sa202010:
          name: ${sa202010_NAME:notprovided}
          key: ${SA202010_KEY:notprovided}
    test:
      name: overridefromkubernetes
    spring:
      cloud:
        azure:
          appconfiguration:
            stores:
              - connection-string: Endpoint=https://replaceme.azconfig.io

