apiVersion: v1
kind: Service
metadata:
  name: azure-appconfig-kubernetes
spec:
  type: LoadBalancer
  selector:
    app: azure-appconfig-kubernetes
  ports:
    - name: http
      port: 8080
      targetPort: 8080